# encoding:utf-8
"""Desktop Web child sessions: bootstrap, status and mutual revocation.

Change ``add-desktop-remote-web-workbench`` (tasks 3.2-3.6).

The shape
---------
The desktop main process holds a *native* ``AuthSession`` (minted by the PKCE
exchange in :mod:`auth.desktop_auth`). It must not hand that Bearer to the Web
page it carries in its container: the page is a browser context and a Bearer
there would be readable by page script and by any injected code. Instead

1. the main process proves it holds the native session (over the wire, as an
   ``Authorization: Bearer`` header -- never a Cookie) and asks for a Web child;
2. the server mints an **independent** session and returns its secret *only* in
   a ``Set-Cookie`` (host-only, HttpOnly, Secure, SameSite=Lax) -- never in the
   JSON body, never as the same value as the native Bearer;
3. the pair is recorded in ``desktop_web_links``, which is what makes the child
   follow the parent: every later request through the ordinary identity seam
   re-checks the parent (task 3.5), and either side logging out tears down both
   (task 3.6).

``bootstrap_id`` is generated by the main process with at least 128 bits of
entropy and is single-use per parent: replaying it answers 409
``bootstrap_consumed`` rather than minting a second child. A *new* id replaces
the child (the old link and its session are revoked in the same transaction), so
a parent never has two live children even across workers -- the partial unique
index from ``auth/store._migration_36`` is the actual guard, not a
check-then-insert.

This module owns no HTTP shape; the handler translates
:class:`DesktopWebSessionError` and delivers the cookie.
"""

from __future__ import annotations

import hmac
import re
import secrets
import time
from typing import Any, Dict, Optional

from auth.session import generate_token, hash_token, session_ttl_seconds

#: The Web-session protocol major this server serves (contracts §2).
WEB_PROTOCOL_MAJOR = 1

#: A bootstrap/instance id is a client-generated high-entropy token. 22 base64url
#: characters carry 132 bits, so 22 is the floor for "at least 128 bits"; the
#: cap keeps a hostile client from writing unbounded rows.
_ID_PATTERN = re.compile(r"\A[A-Za-z0-9_-]{22,128}\Z")

#: Audited actions. Stable strings the audit console filters on.
AUDIT_BOOTSTRAP = "desktop.web-session.bootstrap"
AUDIT_REVOKE = "desktop.web-session.revoke"
AUDIT_REPLAY = "desktop.web-session.replay"

#: The cookie the child secret is delivered in (contracts §2). The name and the
#: attributes below are the same values the desktop client validates
#: (``desktop/src/main/remote/web-session.ts``); ``contracts/desktop/v1.json``
#: ``web_session`` is the single declaration both sides are checked against.
WEB_SESSION_COOKIE = "cow_session"

#: The attributes the contract fixes for the child cookie. Host-only is
#: expressed by *omitting* ``Domain`` -- an attribute list is the honest place
#: to say that, because there is nothing to set.
COOKIE_ATTRIBUTES = "Path=/; HttpOnly; Secure; SameSite=Lax"


def _now() -> int:
    return int(time.time())


class DesktopWebSessionError(RuntimeError):
    """A refused step, carrying the HTTP shape the handler should report."""

    def __init__(self, message: str, code: str = "invalid_request",
                 status: int = 400) -> None:
        super().__init__(message)
        self.code = code
        self.status = status


class DesktopWebSessionService:
    """Bootstrap/status/revoke for one identity database."""

    def __init__(self, identity_service) -> None:
        self._svc = identity_service

    # -- shared guards ------------------------------------------------------

    def _live_native(self, native_token: str):
        """The owner of a live, unrestricted native session, or a refusal."""
        if not native_token:
            raise DesktopWebSessionError("unauthorized", "auth_required", 401)
        session = self._svc.verify_session(native_token)
        if not session:
            raise DesktopWebSessionError("unauthorized", "auth_required", 401)
        user = session["user"]
        if user.get("must_change_password") or session["session"]["restricted"]:
            raise DesktopWebSessionError("password change required",
                                         "password_change_required", 403)
        return user, session["session"]

    @staticmethod
    def _live_session_row(con, session_id: str) -> Optional[Dict[str, Any]]:
        rows = con.execute("SELECT * FROM auth_sessions WHERE id=?",
                           (session_id,)).fetchall()
        if not rows:
            return None
        row = dict(rows[0])
        if row["revoked_at"] or row["expires_at"] <= _now():
            return None
        return row

    # -- 3.3/3.4: bootstrap ------------------------------------------------

    def bootstrap(self, *, native_token: str, bootstrap_id: str,
                  instance_id: str, web_protocol: Any, origin: str) -> Dict[str, Any]:
        """Create (or replace) the Web child session for a native parent.

        Returns the non-secret projection plus ``web_token``, which the caller
        must deliver *only* as a Set-Cookie and must not return in the body.
        """
        if web_protocol != WEB_PROTOCOL_MAJOR:
            raise DesktopWebSessionError("unsupported web protocol",
                                         "protocol_mismatch", 400)
        if not _ID_PATTERN.fullmatch(str(bootstrap_id or "")):
            raise DesktopWebSessionError("invalid bootstrap id", "invalid_request", 400)
        if not _ID_PATTERN.fullmatch(str(instance_id or "")):
            raise DesktopWebSessionError("invalid instance id", "invalid_request", 400)
        if not origin:
            raise DesktopWebSessionError("missing origin", "unsupported_origin", 400)

        user, native = self._live_native(native_token)
        now = _now()
        con = self._svc._tx()
        with con:
            # Re-verify the parent *inside the write lock*: the request-scoped
            # check above could have raced a revocation.
            row = self._live_session_row(con, native["id"])
            if row is None or not hmac.compare_digest(row["token_hash"],
                                                      hash_token(native_token)):
                raise DesktopWebSessionError("unauthorized", "auth_required", 401)

            # The native origin registered at mint time must match this request's
            # origin. A session with no registration cannot bootstrap at all:
            # that is the "re-verify the source" step, not an optional one.
            registered = con.execute(
                "SELECT origin FROM desktop_native_origins WHERE session_id=?",
                (native["id"],)).fetchall()
            if not registered:
                raise DesktopWebSessionError("origin was not registered",
                                             "unsupported_origin", 400)
            if not hmac.compare_digest(registered[0]["origin"], origin):
                raise DesktopWebSessionError("origin mismatch",
                                             "unsupported_origin", 400)

            replay = con.execute(
                "SELECT id FROM desktop_web_links WHERE native_session_id=?"
                " AND bootstrap_id=?", (native["id"], bootstrap_id)).fetchall()
            if replay:
                self._svc._audit.record(
                    actor_user_id=user["id"], actor_username=user["username"],
                    action=AUDIT_REPLAY, target="desktop.web-session",
                    redacted_changes={"bootstrap_id_reused": True},
                    result="denied", con=con)
                raise DesktopWebSessionError("bootstrap id already consumed",
                                             "bootstrap_consumed", 409)

            # A new id replaces the previous child (task 3.4): revoke the old
            # link and its session before inserting the new one.
            for old in con.execute(
                    "SELECT id, web_session_hash FROM desktop_web_links"
                    " WHERE native_session_id=? AND revoked_at IS NULL",
                    (native["id"],)).fetchall():
                con.execute(
                    "UPDATE auth_sessions SET revoked_at=?"
                    " WHERE token_hash=? AND revoked_at IS NULL",
                    (now, old["web_session_hash"]))
                con.execute(
                    "UPDATE desktop_web_links SET revoked_at=?, revoked_reason=?"
                    " WHERE id=?", (now, "replaced", old["id"]))

            web_token = generate_token()
            web_session_id = secrets.token_urlsafe(18)
            expires_at = now + session_ttl_seconds(False)
            con.execute(
                "INSERT INTO auth_sessions (id, token_hash, user_id, expires_at, restricted)"
                " VALUES (?,?,?,?,0)",
                (web_session_id, hash_token(web_token), user["id"], expires_at))
            link_id = secrets.token_urlsafe(18)
            try:
                con.execute(
                    "INSERT INTO desktop_web_links"
                    " (id, native_session_id, native_session_hash, user_id,"
                    "  web_session_id, web_session_hash, bootstrap_id, instance_id,"
                    "  origin, created_at)"
                    " VALUES (?,?,?,?,?,?,?,?,?,?)",
                    (link_id, native["id"], hash_token(native_token), user["id"],
                     web_session_id, hash_token(web_token), bootstrap_id,
                     instance_id, origin, now))
            except Exception:
                # The partial unique index refused a second active child: a
                # concurrent bootstrap won the race. The caller must retry with
                # the winning link, never silently keep two children.
                raise DesktopWebSessionError("another bootstrap is active",
                                             "stale_context", 409)
            self._svc._audit.record(
                actor_user_id=user["id"], actor_username=user["username"],
                action=AUDIT_BOOTSTRAP, target="desktop.web-session",
                redacted_changes={"instance_id": instance_id,
                                  "web_protocol": WEB_PROTOCOL_MAJOR},
                result="success", con=con)
            con.commit()

        return {
            "link_id": link_id,
            "user_id": user["id"],
            "expires_at": expires_at,
            "web_protocol": WEB_PROTOCOL_MAJOR,
            "web_token": web_token,
        }

    # -- 3.4: status -------------------------------------------------------

    def status(self, *, native_token: str) -> Dict[str, Any]:
        """The current link for a parent. Never returns a Cookie or a token."""
        user, native = self._live_native(native_token)
        rows = self._svc._store.execute(
            "SELECT l.id AS link_id, l.user_id, l.created_at,"
            "       s.expires_at AS expires_at"
            " FROM desktop_web_links l"
            " JOIN auth_sessions s ON s.id = l.web_session_id"
            " WHERE l.native_session_id=? AND l.revoked_at IS NULL"
            "   AND s.revoked_at IS NULL AND s.expires_at > ?",
            (native["id"], _now()))
        if not rows:
            return {"state": "none", "user_id": user["id"]}
        row = dict(rows[0])
        return {
            "state": "active",
            "link_id": row["link_id"],
            "user_id": row["user_id"],
            "expires_at": row["expires_at"],
        }

    # -- 3.6: revocation ---------------------------------------------------

    def revoke_for_native(self, native_session_id: str, *,
                          reason: str = "native_logout") -> int:
        """Revoke every live child of a parent session. Idempotent."""
        now = _now()
        revoked = 0
        con = self._svc._tx()
        with con:
            for row in con.execute(
                    "SELECT id, web_session_hash FROM desktop_web_links"
                    " WHERE native_session_id=? AND revoked_at IS NULL",
                    (native_session_id,)).fetchall():
                con.execute(
                    "UPDATE auth_sessions SET revoked_at=?"
                    " WHERE token_hash=? AND revoked_at IS NULL",
                    (now, row["web_session_hash"]))
                con.execute(
                    "UPDATE desktop_web_links SET revoked_at=?, revoked_reason=?"
                    " WHERE id=?", (now, reason, row["id"]))
                revoked += 1
            con.commit()
        return revoked

    def revoke_for_web_session(self, web_session_id: str, *,
                               reason: str = "web_logout") -> int:
        """Revoke a link from the child side, taking the pairing with it.

        A remote Web logout ends the *pairing*, not just the child (task 3.6):
        the native parent session is revoked in the same transaction and every
        sibling link of that parent goes with it. Ordinary independent browser
        sessions of the same account are untouched -- only the two sessions the
        link names are affected.
        """
        now = _now()
        revoked = 0
        con = self._svc._tx()
        with con:
            links = con.execute(
                "SELECT id, native_session_id, native_session_hash,"
                "       web_session_hash FROM desktop_web_links"
                " WHERE web_session_id=? AND revoked_at IS NULL",
                (web_session_id,)).fetchall()
            for link in links:
                row = dict(link)
                # The child that asked, then the native parent it belongs to.
                con.execute(
                    "UPDATE auth_sessions SET revoked_at=?"
                    " WHERE token_hash=? AND revoked_at IS NULL",
                    (now, row["web_session_hash"]))
                con.execute(
                    "UPDATE auth_sessions SET revoked_at=?"
                    " WHERE id=? AND revoked_at IS NULL",
                    (now, row["native_session_id"]))
                # Every link of that parent is part of the same pairing.
                for sibling in con.execute(
                        "SELECT id FROM desktop_web_links"
                        " WHERE native_session_id=? AND revoked_at IS NULL",
                        (row["native_session_id"],)).fetchall():
                    con.execute(
                        "UPDATE desktop_web_links SET revoked_at=?, revoked_reason=?"
                        " WHERE id=?", (now, reason, sibling["id"]))
                    revoked += 1
            con.commit()
        return revoked

    def revoke_by_ticket(self, link_id: str, *, reason: str = "web_logout",
                         native_session_id: Optional[str] = None) -> int:
        """Revoke one link by id, optionally pinning the calling parent."""
        now = _now()
        con = self._svc._tx()
        with con:
            rows = con.execute(
                "SELECT id, web_session_hash, native_session_id FROM desktop_web_links"
                " WHERE id=? AND revoked_at IS NULL", (link_id,)).fetchall()
            if not rows:
                con.commit()
                return 0
            row = dict(rows[0])
            if native_session_id and row["native_session_id"] != native_session_id:
                # A parent may only revoke its own link.
                raise DesktopWebSessionError("not your link",
                                             "permission_denied", 403)
            con.execute(
                "UPDATE auth_sessions SET revoked_at=?"
                " WHERE token_hash=? AND revoked_at IS NULL",
                (now, row["web_session_hash"]))
            con.execute(
                "UPDATE desktop_web_links SET revoked_at=?, revoked_reason=?"
                " WHERE id=?", (now, reason, row["id"]))
            con.commit()
        return 1

    # -- 3.5: the parent check the identity seam calls ---------------------

    def child_link(self, web_session_id: str) -> Optional[Dict[str, Any]]:
        """The live link whose (active) child session is ``web_session_id``."""
        rows = self._svc._store.execute(
            "SELECT * FROM desktop_web_links"
            " WHERE web_session_id=? AND revoked_at IS NULL", (web_session_id,))
        return dict(rows[0]) if rows else None

    def parent_is_live(self, link: Dict[str, Any]) -> bool:
        """Whether a child's native parent is still a valid, active session.

        Checked on *every* request that resolves the child (task 3.5), not only
        at bootstrap: a parent revoked elsewhere must stop the child, and the
        same user/tenant rules must still apply.
        """
        rows = self._svc._store.execute(
            "SELECT * FROM auth_sessions WHERE id=?",
            (link["native_session_id"],))
        if not rows:
            return False
        row = dict(rows[0])
        if row["revoked_at"] or row["expires_at"] <= _now():
            return False
        if not hmac.compare_digest(row["token_hash"], link["native_session_hash"]):
            return False
        user = self._svc._find_user_by_id(link["user_id"])
        if not user or not user["active"]:
            return False
        if user.get("must_change_password"):
            return False
        # The child is never allowed to outlive its parent.
        return True


_SERVICES: Dict[str, DesktopWebSessionService] = {}


def service_for(identity_service) -> DesktopWebSessionService:
    """The child-session service bound to one ``IdentityService``."""
    key = getattr(identity_service._store, "db_path", "") or ""
    service = _SERVICES.get(key)
    if service is None:
        service = DesktopWebSessionService(identity_service)
        _SERVICES[key] = service
    return service
